//! Native plugin package archives and atomic installation (spec 23.3, 23.4).
//!
//! The package format is deliberately small: a ZIP archive contains the native
//! manifest and payload, plus a TOML lock member that authenticates every other
//! member.  Installation validates the complete archive before it changes the
//! installed directory, then swaps complete directories rather than replacing
//! individual files.

use std::collections::{BTreeMap, BTreeSet};
use std::fs::{self, File};
use std::io::{Cursor, Read, Write};
use std::path::{Component, Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

use crikey_plugin_model::{Manifest, Runtime};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use zip::write::SimpleFileOptions;
use zip::{CompressionMethod, ZipArchive, ZipWriter};

use crate::PackageError;

const MANIFEST_MEMBER: &str = "crikey.toml";
const LOCK_MEMBER: &str = "crikey-package.lock";

/// Metadata reported for a validated native package (spec 23.3, 23.4).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NativePackageReport {
    pub plugin: String,
    pub version: String,
    pub os: Vec<String>,
    pub arch: Vec<String>,
    pub entries: Vec<(String, u64)>,
    pub hash: String,
    pub signed: bool,
    pub unsigned_binary: bool,
}

/// A completed native installation and the retained directory used for
/// rollback (spec 23.4).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NativeInstall {
    pub root: PathBuf,
    pub previous: Option<PathBuf>,
    pub report: NativePackageReport,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct PackageLock {
    plugin: String,
    version: String,
    entries: BTreeMap<String, String>,
}

#[derive(Debug)]
struct SourceMember {
    bytes: Vec<u8>,
    unix_mode: Option<u32>,
}

#[derive(Debug)]
struct ArchiveMember {
    bytes: Vec<u8>,
    directory: bool,
    #[cfg_attr(not(unix), allow(dead_code))]
    unix_mode: Option<u32>,
}

#[derive(Debug)]
struct LoadedPackage {
    members: BTreeMap<String, ArchiveMember>,
    manifest: Manifest,
    archive_hash: String,
}

/// Builds a deterministic native ZIP package and returns its validated report.
///
/// Archive paths are sorted, timestamps use the ZIP crate's fixed default (the
/// crate is built without its wall-clock `time` feature), and all payloads are
/// stored.  This satisfies the byte-stable package requirement in amendment
/// §11.3 and spec §23.3.
pub fn build_package(plugin_dir: &Path, out: &Path) -> Result<NativePackageReport, PackageError> {
    let manifest_path = plugin_dir.join(MANIFEST_MEMBER);
    let manifest_bytes = fs::read(&manifest_path)?;
    let manifest = parse_manifest(&manifest_bytes)?;
    validate_manifest_shape(&manifest)?;

    let source_members = collect_source_members(plugin_dir, out)?;
    if !source_members.contains_key(MANIFEST_MEMBER) {
        return Err(PackageError::Manifest(format!(
            "package is missing {MANIFEST_MEMBER}"
        )));
    }
    if source_members.contains_key(LOCK_MEMBER) {
        return Err(PackageError::Manifest(format!(
            "{LOCK_MEMBER} is generated by the package builder"
        )));
    }
    validate_manifest_members(
        &manifest,
        source_members.keys().cloned(),
        std::iter::empty::<String>(),
    )?;

    let entries = source_members
        .iter()
        .map(|(name, member)| (name.clone(), sha256_hex(&member.bytes)))
        .collect::<BTreeMap<_, _>>();
    let lock = PackageLock {
        plugin: manifest.plugin.id.clone(),
        version: manifest.plugin.version.clone(),
        entries,
    };
    let lock_bytes = toml::to_string(&lock)
        .map_err(|error| PackageError::Manifest(format!("could not encode package lock: {error}")))?
        .into_bytes();

    if let Some(parent) = out.parent().filter(|parent| !parent.as_os_str().is_empty()) {
        fs::create_dir_all(parent)?;
    }
    let file = File::create(out)?;
    let mut writer = ZipWriter::new(file);
    for (name, member) in &source_members {
        let options = archive_options(member.unix_mode);
        writer
            .start_file(name.as_str(), options)
            .map_err(|error| PackageError::MalformedArchive(format!("could not create {name}: {error}")))?;
        writer.write_all(&member.bytes)?;
    }
    writer
        .start_file(LOCK_MEMBER, archive_options(None))
        .map_err(|error| {
            PackageError::MalformedArchive(format!("could not create {LOCK_MEMBER}: {error}"))
        })?;
    writer.write_all(&lock_bytes)?;
    writer
        .finish()
        .map_err(|error| PackageError::MalformedArchive(format!("could not finish package: {error}")))?;

    inspect_package(out)
}

/// Inspects and authenticates every member of a native package archive.
pub fn inspect_package(archive: &Path) -> Result<NativePackageReport, PackageError> {
    let package = load_package(archive)?;
    validate_integrity(&package)?;
    Ok(package_report(&package))
}

/// Authenticates a native package and, when supplied, pins its whole-archive
/// SHA-256 to `expected_hash` (spec 23.3).
pub fn verify_package(
    archive: &Path,
    expected_hash: Option<&str>,
) -> Result<NativePackageReport, PackageError> {
    let package = load_package(archive)?;
    validate_integrity(&package)?;
    if let Some(expected) = expected_hash {
        if !is_hex_sha256(expected) || !package.archive_hash.eq_ignore_ascii_case(expected) {
            return Err(PackageError::HashMismatch(format!(
                "archive hash is {}, expected {expected}",
                package.archive_hash
            )));
        }
    }
    Ok(package_report(&package))
}

/// Installs a validated native package by swapping complete directories.  The
/// platform check occurs before embedded-hash verification, and the supplied
/// stop callback is invoked before any existing installation is moved (spec
/// 23.3, 23.4).
pub fn install_native(
    archive: &Path,
    install_root: &Path,
    os: &str,
    arch: &str,
    stop_running: &mut dyn FnMut(&str) -> Result<(), PackageError>,
) -> Result<NativeInstall, PackageError> {
    let package = load_package(archive)?;
    ensure_compatible(&package.manifest, os, arch)?;
    validate_integrity(&package)?;

    stop_running(&package.manifest.plugin.id)?;

    let parent = install_parent(install_root)?;
    if !parent.as_os_str().is_empty() {
        fs::create_dir_all(parent)?;
    }

    let staging = temporary_path(parent, install_root, "staging");
    let stage_result = write_staging(&package, &staging);
    if let Err(error) = stage_result {
        remove_directory_if_present(&staging);
        return Err(error);
    }

    let root_state = inspect_install_root(install_root)?;
    let mut previous = None;
    let mut removed_empty_root = false;
    if root_state == InstallRootState::Populated {
        let backup = temporary_path(parent, install_root, "previous");
        if let Err(error) = fs::rename(install_root, &backup) {
            remove_directory_if_present(&staging);
            return Err(PackageError::Io(error));
        }
        previous = Some(backup);
    } else if root_state == InstallRootState::Empty {
        if let Err(error) = fs::remove_dir(install_root) {
            remove_directory_if_present(&staging);
            return Err(PackageError::Io(error));
        }
        removed_empty_root = true;
    }

    if let Err(error) = fs::rename(&staging, install_root) {
        remove_directory_if_present(&staging);
        if let Some(backup) = previous.as_ref() {
            if let Err(restore) = fs::rename(backup, install_root) {
                return Err(PackageError::Install(format!(
                    "replacement failed ({error}) and restoring the previous version failed ({restore})"
                )));
            }
        } else if removed_empty_root {
            let _ = fs::create_dir(install_root);
        }
        return Err(PackageError::Io(error));
    }

    Ok(NativeInstall {
        root: install_root.to_path_buf(),
        previous,
        report: package_report(&package),
    })
}

/// Restores the retained previous directory with the same complete-directory
/// swap used by installation (spec 23.4).
pub fn rollback_native(install: &NativeInstall) -> Result<(), PackageError> {
    let previous = install
        .previous
        .as_ref()
        .ok_or_else(|| PackageError::Install("no previous native version is retained".to_owned()))?;
    if previous == &install.root {
        return Err(PackageError::Install(
            "previous native version must be separate from the active root".to_owned(),
        ));
    }
    let parent = install_parent(&install.root)?;
    if previous.parent() != Some(parent) {
        return Err(PackageError::Install(
            "previous native version is not beside the active root".to_owned(),
        ));
    }
    let previous_metadata = fs::symlink_metadata(previous).map_err(PackageError::Io)?;
    if !previous_metadata.is_dir() || previous_metadata.file_type().is_symlink() {
        return Err(PackageError::Install(
            "retained previous native version is not a directory".to_owned(),
        ));
    }

    let current_exists = match fs::symlink_metadata(&install.root) {
        Ok(metadata) => {
            if !metadata.is_dir() || metadata.file_type().is_symlink() {
                return Err(PackageError::Install(
                    "active native installation is not a directory".to_owned(),
                ));
            }
            true
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => false,
        Err(error) => return Err(PackageError::Io(error)),
    };

    let displaced = temporary_path(parent, &install.root, "rollback");
    if current_exists {
        if let Err(error) = fs::rename(&install.root, &displaced) {
            return Err(PackageError::Io(error));
        }
    }
    if let Err(error) = fs::rename(previous, &install.root) {
        if current_exists {
            let _ = fs::rename(&displaced, &install.root);
        }
        return Err(PackageError::Io(error));
    }
    if current_exists {
        fs::remove_dir_all(&displaced).map_err(PackageError::Io)?;
    }
    Ok(())
}

fn parse_manifest(bytes: &[u8]) -> Result<Manifest, PackageError> {
    let text = std::str::from_utf8(bytes)
        .map_err(|error| PackageError::Manifest(format!("{MANIFEST_MEMBER} is not UTF-8: {error}")))?;
    Manifest::parse(text).map_err(|error| PackageError::Manifest(error.to_string()))
}

fn validate_manifest_shape(manifest: &Manifest) -> Result<(), PackageError> {
    if manifest.plugin.runtime != Runtime::Native {
        return Err(PackageError::Manifest(
            "native packages require plugin.runtime = \"native\"".to_owned(),
        ));
    }
    if manifest.plugin.id.is_empty() || manifest.plugin.version.is_empty() {
        return Err(PackageError::Manifest(
            "plugin id and version must not be empty".to_owned(),
        ));
    }
    if manifest.plugin.entrypoint.is_empty() {
        return Err(PackageError::Manifest(
            "native package manifest has no entrypoint".to_owned(),
        ));
    }
    Ok(())
}

fn validate_manifest_members<I, D>(manifest: &Manifest, names: I, directories: D) -> Result<(), PackageError>
where
    I: IntoIterator<Item = String>,
    D: IntoIterator<Item = String>,
{
    let names = names.into_iter().collect::<BTreeSet<_>>();
    let directories = directories.into_iter().collect::<BTreeSet<_>>();
    let binary_count = names
        .iter()
        .filter(|name| name.starts_with("bin/") && !name.ends_with('/') && !name.ends_with(".sig"))
        .count();
    if binary_count == 0 {
        return Err(PackageError::Manifest(
            "native package contains no bin/ payload".to_owned(),
        ));
    }
    for entrypoint in manifest.plugin.entrypoint.values() {
        if !names.contains(entrypoint) || directories.contains(entrypoint) {
            return Err(PackageError::Manifest(format!(
                "entrypoint {entrypoint:?} is not a package file"
            )));
        }
    }
    Ok(())
}

fn collect_source_members(
    plugin_dir: &Path,
    out: &Path,
) -> Result<BTreeMap<String, SourceMember>, PackageError> {
    let metadata = fs::symlink_metadata(plugin_dir)?;
    if !metadata.is_dir() || metadata.file_type().is_symlink() {
        return Err(PackageError::Manifest(format!(
            "plugin path {} is not a directory",
            plugin_dir.display()
        )));
    }
    let output_existing = fs::canonicalize(out).ok();
    let mut pending = vec![plugin_dir.to_path_buf()];
    let mut members = BTreeMap::new();
    while let Some(directory) = pending.pop() {
        let mut children = fs::read_dir(&directory)?.collect::<Result<Vec<_>, _>>()?;
        children.sort_by_key(|entry| entry.path());
        for entry in children {
            let path = entry.path();
            let file_type = entry.file_type()?;
            if file_type.is_symlink() {
                return Err(PackageError::Manifest(format!(
                    "symbolic links are not allowed in native packages: {}",
                    path.display()
                )));
            }
            if file_type.is_dir() {
                pending.push(path);
                continue;
            }
            if !file_type.is_file() {
                return Err(PackageError::Manifest(format!(
                    "unsupported package member type: {}",
                    path.display()
                )));
            }
            let is_output = output_existing
                .as_ref()
                .and_then(|output| {
                    fs::canonicalize(&path)
                        .ok()
                        .map(|candidate| candidate.as_path() == output.as_path())
                })
                .unwrap_or(false);
            if is_output {
                continue;
            }
            let relative = path.strip_prefix(plugin_dir).map_err(|_| {
                PackageError::Manifest(format!("package member escaped {}", plugin_dir.display()))
            })?;
            let name = source_archive_name(relative)?;
            if name == LOCK_MEMBER {
                return Err(PackageError::Manifest(format!(
                    "{LOCK_MEMBER} is generated by the package builder"
                )));
            }
            let bytes = fs::read(&path)?;
            let unix_mode = file_mode(&path)?;
            if members
                .insert(name.clone(), SourceMember { bytes, unix_mode })
                .is_some()
            {
                return Err(PackageError::Manifest(format!("duplicate package member {name}")));
            }
        }
    }
    Ok(members)
}

fn source_archive_name(relative: &Path) -> Result<String, PackageError> {
    let mut parts = Vec::new();
    for component in relative.components() {
        let Component::Normal(part) = component else {
            return Err(PackageError::Manifest(format!(
                "unsafe package path {}",
                relative.display()
            )));
        };
        let Some(part) = part.to_str() else {
            return Err(PackageError::Manifest(format!(
                "package path {} is not UTF-8",
                relative.display()
            )));
        };
        if part.is_empty() || part.contains(['/', '\\', ':']) {
            return Err(PackageError::Manifest(format!(
                "unsafe package path {}",
                relative.display()
            )));
        }
        parts.push(part);
    }
    if parts.is_empty() {
        return Err(PackageError::Manifest("empty package path".to_owned()));
    }
    Ok(parts.join("/"))
}

fn load_package(archive: &Path) -> Result<LoadedPackage, PackageError> {
    let archive_bytes = fs::read(archive)?;
    let archive_hash = sha256_hex(&archive_bytes);
    let mut zip = ZipArchive::new(Cursor::new(archive_bytes.as_slice()))
        .map_err(|error| PackageError::MalformedArchive(error.to_string()))?;
    let mut members = BTreeMap::new();
    for index in 0..zip.len() {
        let mut entry = zip
            .by_index_raw(index)
            .map_err(|error| PackageError::MalformedArchive(error.to_string()))?;
        let raw_name = entry.name_raw().to_vec();
        let name = std::str::from_utf8(&raw_name)
            .map_err(|error| PackageError::MalformedArchive(format!("entry name is not UTF-8: {error}")))?
            .to_owned();
        let directory = entry.is_dir() || name.ends_with('/');
        validate_archive_name(&name, directory)?;
        if entry.is_symlink() {
            return Err(PackageError::MalformedArchive(format!(
                "symbolic-link entry {name} is not allowed"
            )));
        }
        let mut bytes = Vec::new();
        entry
            .read_to_end(&mut bytes)
            .map_err(|error| PackageError::MalformedArchive(format!("could not read {name}: {error}")))?;
        if directory && !bytes.is_empty() {
            return Err(PackageError::MalformedArchive(format!(
                "directory entry {name} has a payload"
            )));
        }
        if members
            .insert(
                name.clone(),
                ArchiveMember {
                    bytes,
                    directory,
                    unix_mode: entry.unix_mode(),
                },
            )
            .is_some()
        {
            return Err(PackageError::MalformedArchive(format!(
                "duplicate archive member {name}"
            )));
        }
    }

    let manifest_member = members
        .get(MANIFEST_MEMBER)
        .ok_or_else(|| PackageError::Manifest(format!("package is missing {MANIFEST_MEMBER}")))?;
    if manifest_member.directory {
        return Err(PackageError::Manifest(format!(
            "{MANIFEST_MEMBER} must be a file"
        )));
    }
    let manifest = parse_manifest(&manifest_member.bytes)?;
    validate_manifest_shape(&manifest)?;
    let names = members.keys().cloned().collect::<Vec<_>>();
    let directories = members
        .iter()
        .filter(|(_, member)| member.directory)
        .map(|(name, _)| name.clone())
        .collect::<Vec<_>>();
    validate_manifest_members(&manifest, names, directories)?;
    validate_archive_prefixes(&members)?;

    Ok(LoadedPackage {
        members,
        manifest,
        archive_hash,
    })
}

fn validate_archive_name(name: &str, directory: bool) -> Result<(), PackageError> {
    let without_slash = if directory {
        name.strip_suffix('/').unwrap_or(name)
    } else {
        name
    };
    if without_slash.is_empty()
        || name.as_bytes().contains(&0)
        || name.starts_with('/')
        || name.starts_with('\\')
        || (!directory && name.ends_with('/'))
    {
        return Err(PackageError::MalformedArchive(format!(
            "unsafe archive member path {name:?}"
        )));
    }
    for part in without_slash.split('/') {
        if part.is_empty() || part == "." || part == ".." || part.contains(['\\', ':']) {
            return Err(PackageError::MalformedArchive(format!(
                "unsafe archive member path {name:?}"
            )));
        }
    }
    Ok(())
}

fn validate_archive_prefixes(members: &BTreeMap<String, ArchiveMember>) -> Result<(), PackageError> {
    for name in members.keys() {
        let mut prefix = String::new();
        for (index, part) in name.split('/').enumerate() {
            if index > 0 {
                prefix.push('/');
            }
            prefix.push_str(part);
            if prefix.as_str() != name.as_str()
                && members.get(&prefix).is_some_and(|candidate| !candidate.directory)
            {
                return Err(PackageError::MalformedArchive(format!(
                    "archive member {name} conflicts with file {prefix}"
                )));
            }
        }
    }
    Ok(())
}

fn validate_integrity(package: &LoadedPackage) -> Result<(), PackageError> {
    let lock_member = package
        .members
        .get(LOCK_MEMBER)
        .ok_or_else(|| PackageError::HashMismatch(format!("package is missing {LOCK_MEMBER}")))?;
    if lock_member.directory {
        return Err(PackageError::HashMismatch(format!(
            "{LOCK_MEMBER} is a directory"
        )));
    }
    let lock_text = std::str::from_utf8(&lock_member.bytes)
        .map_err(|error| PackageError::HashMismatch(format!("{LOCK_MEMBER} is not UTF-8: {error}")))?;
    let lock: PackageLock = toml::from_str(lock_text)
        .map_err(|error| PackageError::HashMismatch(format!("invalid {LOCK_MEMBER}: {error}")))?;
    let canonical_lock = toml::to_string(&lock)
        .map_err(|error| PackageError::HashMismatch(format!("could not encode {LOCK_MEMBER}: {error}")))?;
    if lock_text.as_bytes() != canonical_lock.as_bytes() {
        return Err(PackageError::HashMismatch(format!(
            "{LOCK_MEMBER} is not in canonical form"
        )));
    }
    if lock.plugin != package.manifest.plugin.id || lock.version != package.manifest.plugin.version {
        return Err(PackageError::HashMismatch(format!(
            "{LOCK_MEMBER} identity does not match crikey.toml"
        )));
    }

    let actual_names = package
        .members
        .keys()
        .filter(|name| name.as_str() != LOCK_MEMBER)
        .cloned()
        .collect::<BTreeSet<_>>();
    let expected_names = lock.entries.keys().cloned().collect::<BTreeSet<_>>();
    if actual_names != expected_names {
        return Err(PackageError::HashMismatch(format!(
            "{LOCK_MEMBER} does not list exactly every archive member"
        )));
    }
    for name in actual_names {
        let expected = lock
            .entries
            .get(&name)
            .ok_or_else(|| PackageError::HashMismatch(format!("{LOCK_MEMBER} has no digest for {name}")))?;
        let actual = sha256_hex(&package.members[&name].bytes);
        if !is_hex_sha256(expected) || expected != &actual {
            return Err(PackageError::HashMismatch(format!(
                "digest mismatch for archive member {name}"
            )));
        }
    }
    Ok(())
}

fn ensure_compatible(manifest: &Manifest, os: &str, arch: &str) -> Result<(), PackageError> {
    let os_ok = manifest.platform.os.is_empty() || manifest.platform.os.iter().any(|value| value == os);
    let arch_ok =
        manifest.platform.arch.is_empty() || manifest.platform.arch.iter().any(|value| value == arch);
    if !os_ok || !arch_ok {
        return Err(PackageError::IncompatiblePlatform);
    }
    if manifest.entrypoint_for(os, arch).is_err() {
        return Err(PackageError::MissingEntrypoint {
            os: os.to_owned(),
            arch: arch.to_owned(),
        });
    }
    Ok(())
}

fn package_report(package: &LoadedPackage) -> NativePackageReport {
    let unsigned_binary = package.members.iter().any(|(name, member)| {
        if !name.starts_with("bin/") || member.directory || name.ends_with(".sig") {
            return false;
        }
        match package.members.get(&format!("{name}.sig")) {
            Some(signature) => signature.directory,
            None => true,
        }
    });
    NativePackageReport {
        plugin: package.manifest.plugin.id.clone(),
        version: package.manifest.plugin.version.clone(),
        os: package.manifest.platform.os.clone(),
        arch: package.manifest.platform.arch.clone(),
        entries: package
            .members
            .iter()
            .map(|(name, member)| (name.clone(), member.bytes.len() as u64))
            .collect(),
        hash: package.archive_hash.clone(),
        signed: false,
        unsigned_binary,
    }
}

fn write_staging(package: &LoadedPackage, staging: &Path) -> Result<(), PackageError> {
    fs::create_dir_all(staging)?;
    for (name, member) in &package.members {
        let destination = staging.join(name);
        if member.directory {
            fs::create_dir_all(&destination)?;
            continue;
        }
        if let Some(parent) = destination.parent() {
            fs::create_dir_all(parent)?;
        }
        let mut file = File::create(&destination)?;
        file.write_all(&member.bytes)?;
        #[cfg(unix)]
        if let Some(mode) = member.unix_mode {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&destination, fs::Permissions::from_mode(mode & 0o7777))?;
        }
    }
    Ok(())
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum InstallRootState {
    Missing,
    Empty,
    Populated,
}

fn inspect_install_root(root: &Path) -> Result<InstallRootState, PackageError> {
    let metadata = match fs::symlink_metadata(root) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            return Ok(InstallRootState::Missing);
        }
        Err(error) => return Err(PackageError::Io(error)),
    };
    if metadata.file_type().is_symlink() || !metadata.is_dir() {
        return Err(PackageError::Install(format!(
            "install root {} is not a directory",
            root.display()
        )));
    }
    let mut entries = fs::read_dir(root)?;
    if entries.next().transpose()?.is_none() {
        Ok(InstallRootState::Empty)
    } else {
        Ok(InstallRootState::Populated)
    }
}

fn install_parent(root: &Path) -> Result<&Path, PackageError> {
    root.parent()
        .ok_or_else(|| PackageError::Install(format!("install root {} has no parent", root.display())))
}

fn temporary_path(parent: &Path, root: &Path, kind: &str) -> PathBuf {
    static NEXT: AtomicU64 = AtomicU64::new(0);
    let base = root
        .file_name()
        .map_or_else(|| "native".to_owned(), |name| name.to_string_lossy().into_owned());
    loop {
        let sequence = NEXT.fetch_add(1, Ordering::Relaxed);
        let candidate = parent.join(format!(".{base}.{kind}-{}-{sequence}", std::process::id()));
        if !candidate.exists() {
            return candidate;
        }
    }
}

fn remove_directory_if_present(path: &Path) {
    let _ = fs::remove_dir_all(path);
}

fn file_mode(path: &Path) -> Result<Option<u32>, PackageError> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        Ok(Some(fs::metadata(path)?.permissions().mode()))
    }
    #[cfg(not(unix))]
    {
        let _ = path;
        Ok(None)
    }
}

fn archive_options(mode: Option<u32>) -> SimpleFileOptions {
    let mut options = SimpleFileOptions::default().compression_method(CompressionMethod::Stored);
    if let Some(mode) = mode {
        options = options.unix_permissions(mode);
    }
    options
}

fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    let mut output = String::with_capacity(64);
    for byte in digest {
        output.push_str(&format!("{byte:02x}"));
    }
    output
}

fn is_hex_sha256(value: &str) -> bool {
    value.len() == 64
        && value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}
