[package]
name = "crikey-platform-linux"
description = "Linux platform backend."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
crikey-core.workspace = true
crikey-platform.workspace = true
