[package]
name = "crikey-ui"
description = "Launcher window, view model and presentation contracts."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
crikey-core.workspace = true
egui = { workspace = true, features = ["default_fonts"] }
egui-wgpu.workspace = true
egui-winit = { workspace = true, features = ["clipboard"] }
pollster.workspace = true
thiserror.workspace = true
wgpu = { workspace = true, features = ["dx12", "metal", "wgsl"] }
winit = { workspace = true, features = ["rwh_06", "wayland", "wayland-dlopen", "x11"] }
